### ISSUE TITLE
Refactoring della classe ResearchMethod

### ISSUE THREAD

**Issue by aegroto** [develhope/Java23-Team1-Warehouse#16]
https://github.com/develhope/Java23-Team1-Warehouse/blob/8fb071b9cd7930450dbdbccefeedf16732563784/src/ResearchMethod.java#L6

L'approccio del voler dividere la logica di ricerca dei prodotti del resto della classe Warehouse è corretto. Tuttavia, strutturerei il codice in questo modo:

- Un'interfaccia ProductFilter con un metodo isInFilter(Product) che ritorna true se il prodotto passato come parametro rispetta i criteri del filtro
- Un'implementazione di ProductFilter per ogni tipologia di filtro. Esempio, la classe BuyPriceProductFilter avrà un prezzo minimo e massimo ed il suo metodo isInFilter ritornerà true se il prodotto passato come parametro ha un prezzo d'acquisto all'interno del range
- Un metodo search(ProductFilter) in Warehouse che scorre tutta la lista di prodotti in magazzino e ritorna una nuova lista contenente solo i prodotti per cui il filtro passato come parametro ritorna true. Questo metodo diventerebbe facile da estendere anche all'applicazione di più filtri.

**Comment by hatefulTtamer** [comment]
Done
